export const ARTICLE_INIT_FEATURED = 'ARTICLE_INIT_FEATURED';
export const ARTICLE_INIT_TIPS = 'ARTICLE_INIT_TIPS';

export const MERCHANDISE_INIT_FEATURED = 'MERCHANDISE_INIT_FEATURED';

export const EDIT_PRODUCT_VIEW_MODE = 'EDIT_PRODUCT_VIEW_MODE';
export const EDIT_PRODUCT_DETAIL = 'EDIT_PRODUCT_DETAIL';
export const FEED_EDIT_SORT = 'FEED_EDIT_SORT';
export const FEED_EDIT_FILTER = 'FEED_EDIT_FILTER';
export const PRODUCT_EDIT_SORT = 'PRODUCT_EDIT_SORT';
export const PRODUCT_EDIT_FILTER = 'PRODUCT_EDIT_FILTER';
export const INIT_PRODUCTS = 'INIT_PRODUCTS';
export const INIT_FEEDS = 'INIT_FEEDS';

export const INIT_CART = 'INIT_CART';
export const CART_DELETE_ITEM = 'CART_DELETE_ITEM';
export const CART_UPDATE_ITEM = 'CART_UPDATE_ITEM';
export const CART_UPDATE_ORDER_INFO = 'CART_UPDATE_ORDER_INFO';

export const COLLECTION_INIT_ITEMS = 'COLLECTION_INIT_ITEMS';

export const CART_EDIT_VARIANT = 'CART_EDIT_VARIANT';
export const CART_SAVE_PRODUCT_TO_CART = 'CART_SAVE_PRODUCT_TO_CART';
export const CART_EMPTY_PRODUCT_VARIANT = 'CART_EMPTY_PRODUCT_VARIANT';
export const CART_INIT_SHOPPING_CART = 'CART_INIT_SHOPPING_CART';
export const CART_OPERATE_SHOPPING_CART = 'CART_OPERATE_SHOPPING_CART';
export const CART_EDIT_BILLING_DETAIL = 'CART_EDIT_BILLING_DETAIL';
export const CART_EMPTY_BILLING_DETAIL = 'CART_EMPTY_BILLING_DETAIL';
export const COMMON_EDIT_SEARCH_BAR = 'COMMON_EDIT_SEARCH_BAR';
export const AUTH_INIT_TOKEN = 'AUTH_INIT_TOKEN';
export const CATEGORY_INIT_CATEGORY = 'CATEGORY_INIT_CATEGORY';
export const COMMON_INIT_MY_CREDIT = 'COMMON_INIT_MY_CREDIT';
export const AUTH_INIT_USER_PROFILE = 'AUTH_INIT_USER_PROFILE';
export const COMMON_INIT_SEARCH_BAR = 'COMMON_INIT_SEARCH_BAR';
export const COMMON_INIT_SHOP_INFO = 'COMMON_INIT_SHOP_INFO';
