export const EDIT_PRODUCT_VIEW_MODE = 'EDIT_PRODUCT_VIEW_MODE'
export const EDIT_PRODUCT_DETAIL = 'EDIT_PRODUCT_DETAIL'
export const FEED_EDIT_SORT ='FEED_EDIT_SORT'
export const FEED_EDIT_FILTER ='FEED_EDIT_FILTER'

export const PRODUCT_EDIT_SORT ='PRODUCT_EDIT_SORT'
export const PRODUCT_EDIT_FILTER ='PRODUCT_EDIT_FILTER'
export const INIT_PRODUCTS = 'INIT_PRODUCTS'
export const INIT_FEEDS = 'INIT_FEEDS'