export const EDIT_PRODUCT_VIEW_MODE = 'EDIT_PRODUCT_VIEW_MODE'
export const EDIT_PRODUCT_DETAIL = 'EDIT_PRODUCT_DETAIL'
export const INIT_PRODUCTS = 'INIT_PRODUCTS'
export const INIT_FEEDS = 'INIT_FEEDS'